config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :invoices do
    member do
      get :xhr_change_client_name
      patch :xhr_change_client_name
    end
    resources :purchase_orders, except: :index
  end

  get '/purchase_orders', to: 'purchase_orders#index'
  root to: 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :purchase_orders, dependent: :destroy

  validates :client_name, presence: true, uniqueness: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  def total
    if tax.present?
      amount * (1 + (tax / 100))
    else
      amount
    end
  end
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :invoice

  enum status: { draft: 0, paid: 1, delivered: 2 }

  validates :client_name, :amount, :vendor, :status, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :find_invoice, only: %w[destroy xhr_change_client_name]

  def index
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoices_path, notice: I18n.t('resource.created', resource: 'Invoice') }
      else
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @invoice.destroy!

    redirect_to invoices_path, notice: I18n.t('resource.deleted_for', resource: 'Invoice', for: @invoice.client_name)
  end

  def xhr_change_client_name
    if request.get?
      render partial: 'modal--change-client-name', locals: { invoice: @invoice }
    elsif request.patch?
      @invoice.client_name = params[:invoice][:client_name]
      if @invoice.save
        render json: { id: @invoice.id, client_name: @invoice.client_name }
      else
        render json: @invoice.errors.full_messages.first
      end
    end
  end

  private

  def find_invoice
    @invoice = Invoice.find params[:id]
  end

  def invoice_params
    params.require(:invoice).permit(:client_name, :amount, :tax)
  end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :find_invoice, except: :destroy
  before_action :find_purchase_order, only: %w[edit update destroy]

  def index
    @purchase_orders = PurchaseOrder.all
  end

  def new
    @purchase_order = PurchaseOrder.new(purchase_order_attrs)
  end

  def create
    @purchase_order = @invoice.purchase_orders.build(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to purchase_orders_path, notice: I18n.t('resource.created', resource: 'Purchase Order') }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to purchase_orders_path, notice: I18n.t('resource.updated', resource: 'Purchase Order') }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @purchase_order.destroy
        format.html do
          redirect_to purchase_orders_path, notice: I18n.t('resource.destroyed', resource: 'Purchase Order')
        end
      else
        format.html do
          redirect_to purchase_orders_path, notice: I18n.t('resource.deleted_error', resource: 'Purchase Order')
        end
      end
    end
  end

  private

  def find_invoice
    @invoice = Invoice.find_by(id: params[:invoice_id])
  end

  def find_purchase_order
    @purchase_order = PurchaseOrder.find(params[:id])
  end

  def purchase_order_params
    params.require(:purchase_order).permit(:client_name, :amount, :tax, :vendor, :status)
  end

  def purchase_order_attrs
    return {} unless @invoice

    @invoice.attributes.slice('client_name', 'amount', 'tax')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/purchase_order_helper.rb
module PurchaseOrderHelper
  def total(amount, tax)
    return (amount * (1 + (tax / 100))) if tax.present?

    amount
  end
end

app/views/invoices/_form.html.erb
<%= form_for @invoice, html: { class: 'w-100' } do |f| %>
  <%- if @invoice.errors.any? %>
    <ul>
      <%- @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  <%end%>

  <div class="columns">
    <%= f.label :client_name, class: 'label' %>
    <%= f.text_field :client_name, class: 'field', required: true, placeholder: 'Enter Client Name' %>
  </div>

  <div class="columns">
    <%= f.label :amount, class: 'label' %>
    <%= f.number_field :amount, class: 'field', required: true, min: 0, step: 0.01 %>
  </div>

  <div class="columns">
    <%= f.label :tax, class: 'label' %>
    <%= f.number_field :tax, class: 'field', min: 0, step: 0.01 %>
  </div>

  <div class="columns">
    <%= f.submit class: 'button button-primary' %>
    <%= link_to 'Cancel', invoices_path, class: 'button button-secondary' %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<tr class="invoices-table__item-tr" data-id="<%= invoice.id %>">
  <td class="invoices-table__item-td invoices-table__item-td--client-name"><%= invoice.client_name %></td>
  <td class="invoices-table__item-td"><%= number_to_currency invoice.amount %></td>
  <td class="invoices-table__item-td"><%= invoice.tax %></td>
  <td class="invoices-table__item-td"><%= number_to_currency invoice.total %></td>
  <td class="invoices-table__item-td invoices-table__item-td--actions">
    <%= link_to '', xhr_change_client_name_invoice_path(invoice), class: 'invoice-action invoice-action--edit-name', rel: 'modal:ajax-open', title: 'Change name' %>
    <%= link_to '', new_invoice_purchase_order_path(invoice_id: invoice.id), class: 'invoice-action invoice-action--create-purchase-order' %>
    <%= link_to '', invoice_path(invoice), method: :delete, class: 'invoice-action invoice-action--delete', title: 'Delete invoice' %>
  </td>
</tr>

app/views/invoices/_modal--change-client-name.html.erb
<div class="modal modal--change-client-name">
  <div class="modal__header">
    Change Client Name
  </div>
  <%= form_with model: invoice, url: xhr_change_client_name_invoice_path(invoice), class: 'modal__form' do |f| %>
    <%= f.text_field :client_name, class: 'field field--client-name' %>
    <div class="error-message error-message--client-name"></div>

    <div class="modal__buttons-container">
      <button class="p-button">Change</button>
    </div>
  <% end %>
</div>

app/views/invoices/index.html.erb
<div class="row justify-content-end">
  <%= link_to 'New Invoice', new_invoice_path, class: 'button button-success' %>
</div>
<table class="invoices-table">
  <thead>
    <tr>
      <th class="invoices-table__header invoices-table__header--sortable">
        Client Name
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Amount
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Tax
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Total
      </th>
      <th class="invoices-table__header"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'invoice', collection: @invoices  %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<h1 class="text-2xl font-bold mb-6">New Invoice</h1>
<div class="row">
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200italic,300,400,600,700,400italic,600italic,700italic',
      '/assets/css/application.css'
    %>
  </head>

  <body>
    <header class="header header--sticky">

    </header>

    <main class="main">
      <% flash.each do |type, message| %>
        <div class="flash flash--<%= type %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <%= javascript_include_tag '//code.jquery.com/jquery-3.1.1.min.js',
      '//cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.js',
      '//cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.8.0/jquery.modal.min.js',
      '/assets/js/application.js'
    %>
  </body>
</html>

app/views/purchase_orders/_form.html.erb
<%= form_for [@invoice, @purchase_order], html: { class: 'w-100' } do |f| %>
  <%- if @purchase_order.errors.any? %>
    <ul>
      <%- @purchase_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  <%end%>

  <div class="columns">
    <%= f.label :client_name, class: 'label' %>
    <%= f.text_field :client_name, class: 'field', required: true, placeholder: 'Enter Client Name' %>
  </div>

  <div class="columns">
    <%= f.label :amount, class: 'label' %>
    <%= f.number_field :amount, class: 'field', required: true, min: 0, step: 0.01 %>
  </div>

  <div class="columns">
    <%= f.label :tax, class: 'label' %>
    <%= f.number_field :tax, class: 'field', min: 0, step: 0.01 %>
  </div>

  <div class="columns">
    <%= f.label :vendor, class: 'label' %>
    <%= f.text_field :vendor, class: 'field', required: true, placeholder: 'Enter Vendor Name' %>
  </div>

  <div class="columns">
    <%= f.label :status, class: 'label' %>
    <%= f.select :status, options_for_select(PurchaseOrder.statuses.keys, @purchase_order.status), { include_blank: 'Select Order Status' }, class: 'field', required: true %>
  </div>

  <div class="columns">
    <%= f.submit 'Save', class: 'button button-primary' %>
    <%= link_to 'Cancel', invoices_path, class: 'button button-secondary' %>
  </div>
<% end %>

app/views/purchase_orders/_purchase_order.html.erb
<tr class="invoices-table__item-tr" data-id="<%= purchase_order.id %>">
  <td class="invoices-table__item-td invoices-table__item-td--client-name"><%= purchase_order.client_name %></td>
  <td class="invoices-table__item-td"><%= number_to_currency purchase_order.amount %></td>
  <td class="invoices-table__item-td"><%= purchase_order.tax %></td>
  <td class="invoices-table__item-td">
    <%= number_to_currency total(purchase_order.amount, purchase_order.tax) %></td>
  <td class="invoices-table__item-td"><%= purchase_order.vendor %></td>
  <td class="invoices-table__item-td"><%= purchase_order.status %></td>
  <td class="invoices-table__item-td invoices-table__item-td--actions">
    <%= link_to '', edit_invoice_purchase_order_path(purchase_order.invoice_id, purchase_order.id), class: 'invoice-action invoice-action--edit-name', title: 'Change name' %>
    <%= link_to '', invoice_purchase_order_path(purchase_order.invoice_id, purchase_order.id), method: :delete, class: 'invoice-action invoice-action--delete', title: 'Delete invoice' %>
  </td>
</tr>

app/views/purchase_orders/edit.html.erb
<h1 class="text-2xl font-bold mb-6">Edit Purchase Order</h1>
<div class="row">
  <%= render 'form' %>
</div>

app/views/purchase_orders/index.html.erb
<table class="invoices-table">
  <thead>
    <tr>
      <th class="invoices-table__header invoices-table__header--sortable">
        Client Name
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Amount
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Tax
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Total
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Vendor
      </th>
      <th class="invoices-table__header invoices-table__header--sortable">
        Status
      </th>
      <th class="invoices-table__header"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'purchase_order', collection: @purchase_orders  %>
  </tbody>
</table>

app/views/purchase_orders/new.html.erb
<h1 class="text-2xl font-bold mb-6">Edit Purchase Order</h1>
<div class="row">
  <%= render 'form' %>
</div>